'use client';

import {
  CheckCircleIcon,
} from '@heroicons/react/24/outline';
import type { ScopeDocument as ScopeDocumentType } from '@/lib/mock-data/checklist-data';

interface ScopeDocumentProps {
  scope: ScopeDocumentType;
}

export default function ScopeDocument({ scope }: ScopeDocumentProps) {
  return (
    <article
      className="rounded-xl border border-[#00a9e033] bg-white p-5 shadow-sm transition-all dark:border-zinc-800 dark:bg-zinc-900 sm:p-6"
      aria-label="Scope of Work"
    >
      {/* Header */}
      <header className="mb-4">
        <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-50">
          Scope of Work
        </h2>
      </header>

      {/* Summary */}
      <div className="mb-5">
        <p className="text-sm leading-relaxed text-zinc-700 dark:text-zinc-300">
          {scope.summary}
        </p>
      </div>

      {/* Code References */}
      {scope.codeReferences && scope.codeReferences.length > 0 && (
        <div className="mb-5">
          <h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500 dark:text-zinc-400">
            Code References
          </h3>
          <div className="flex flex-wrap gap-2">
            {scope.codeReferences.map((ref, idx) => (
              <span
                key={idx}
                className="rounded-full bg-blue-50 px-3 py-1 text-xs font-medium text-blue-700 dark:bg-blue-900/30 dark:text-blue-300"
              >
                {ref.code}: {ref.section}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Permit Requirements */}
      {scope.permitRequirements && scope.permitRequirements.length > 0 && (
        <div className="mb-5">
          <h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500 dark:text-zinc-400">
            Permit Requirements
          </h3>
          <ul className="space-y-2" role="list">
            {scope.permitRequirements.map((permit, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <CheckCircleIcon
                  className="mt-0.5 h-4 w-4 shrink-0 text-emerald-500"
                  aria-hidden="true"
                />
                <span className="text-sm font-medium text-zinc-800 dark:text-zinc-200">
                  {permit}
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Generated By Footer */}
      {scope.generatedBy && (
        <footer className="border-t border-zinc-100 pt-3 dark:border-zinc-800">
          <p className="text-xs text-zinc-400 dark:text-zinc-500">
            Generated by Sherpa Platform
          </p>
        </footer>
      )}
    </article>
  );
}
