/**
 * Seeded Pro Profiles — 70 pros across 7 trade categories (10 each)
 *
 * Used for beta testing. Nationally diversified, realistic data.
 * All monetary values in integer cents.
 */

export type ProTier = 'gold' | 'silver' | 'bronze';

export interface SeededPro {
  id: string;
  name: string;
  email: string;
  phone: string;
  trade: string;
  secondaryTrades: string[];
  rating: number;
  reviewCount: number;
  hourlyRateMinCents: number;
  hourlyRateMaxCents: number;
  city: string;
  state: string;
  yearsExperience: number;
  tier: ProTier;
  available: boolean;
  bio: string;
  specialties: string[];
  licenseVerified: boolean;
  insuranceVerified: boolean;
}

// Helper to generate consistent IDs
const p = (n: number) => `sp-${String(n).padStart(3, '0')}`;

export const SEEDED_PROS: SeededPro[] = [
  // ── Plumbing (10) ─────────────────────────────────────────────────
  { id: p(1), name: 'Marcus Rivera', email: 'marcus.r@test.com', phone: '(603) 555-0101', trade: 'Plumbing', secondaryTrades: ['HVAC'], rating: 4.9, reviewCount: 87, hourlyRateMinCents: 8500, hourlyRateMaxCents: 12500, city: 'Portsmouth', state: 'NH', yearsExperience: 18, tier: 'gold', available: true, bio: 'Master plumber with 18 years on residential and commercial systems. Fast response, fair pricing.', specialties: ['pipe repair', 'water heater', 'bathroom remodel'], licenseVerified: true, insuranceVerified: true },
  { id: p(2), name: 'Priya Sharma', email: 'priya.s@test.com', phone: '(512) 555-0102', trade: 'Plumbing', secondaryTrades: [], rating: 4.7, reviewCount: 54, hourlyRateMinCents: 7500, hourlyRateMaxCents: 11000, city: 'Austin', state: 'TX', yearsExperience: 12, tier: 'silver', available: true, bio: 'Licensed plumber specializing in drain cleaning and sewer line repair across central Texas.', specialties: ['drain cleaning', 'sewer', 'leak detection'], licenseVerified: true, insuranceVerified: true },
  { id: p(3), name: 'Tony DeLuca', email: 'tony.d@test.com', phone: '(720) 555-0103', trade: 'Plumbing', secondaryTrades: ['Gas Line'], rating: 4.8, reviewCount: 92, hourlyRateMinCents: 9000, hourlyRateMaxCents: 13000, city: 'Denver', state: 'CO', yearsExperience: 22, tier: 'gold', available: false, bio: 'Veteran plumber and gas line specialist. Code-compliant work guaranteed.', specialties: ['gas line', 'sump pump', 'water filtration'], licenseVerified: true, insuranceVerified: true },
  { id: p(4), name: 'Keisha Brown', email: 'keisha.b@test.com', phone: '(404) 555-0104', trade: 'Plumbing', secondaryTrades: [], rating: 4.5, reviewCount: 32, hourlyRateMinCents: 7000, hourlyRateMaxCents: 10000, city: 'Atlanta', state: 'GA', yearsExperience: 8, tier: 'silver', available: true, bio: 'Focused on residential plumbing — fixture installs, remodels, and emergency repairs.', specialties: ['fixture install', 'bathroom remodel', 'leak detection'], licenseVerified: true, insuranceVerified: true },
  { id: p(5), name: 'Jake Olsen', email: 'jake.o@test.com', phone: '(206) 555-0105', trade: 'Plumbing', secondaryTrades: [], rating: 4.3, reviewCount: 19, hourlyRateMinCents: 6500, hourlyRateMaxCents: 9500, city: 'Seattle', state: 'WA', yearsExperience: 5, tier: 'bronze', available: true, bio: 'Reliable plumber for everyday repairs and new construction rough-ins.', specialties: ['pipe repair', 'drain cleaning', 'fixture install'], licenseVerified: true, insuranceVerified: false },
  { id: p(6), name: 'Carmen Reyes', email: 'carmen.r@test.com', phone: '(305) 555-0106', trade: 'Plumbing', secondaryTrades: ['Irrigation'], rating: 4.6, reviewCount: 41, hourlyRateMinCents: 7500, hourlyRateMaxCents: 11500, city: 'Miami', state: 'FL', yearsExperience: 14, tier: 'silver', available: true, bio: 'South Florida plumbing pro — water heaters, re-piping, and irrigation tie-ins.', specialties: ['water heater', 'pipe repair', 'sump pump'], licenseVerified: true, insuranceVerified: true },
  { id: p(7), name: 'Dmitri Volkov', email: 'dmitri.v@test.com', phone: '(718) 555-0107', trade: 'Plumbing', secondaryTrades: [], rating: 4.8, reviewCount: 73, hourlyRateMinCents: 9500, hourlyRateMaxCents: 14000, city: 'Brooklyn', state: 'NY', yearsExperience: 20, tier: 'gold', available: true, bio: '20 years in NYC plumbing. Brownstones, high-rises, and commercial kitchens.', specialties: ['sewer', 'gas line', 'water filtration'], licenseVerified: true, insuranceVerified: true },
  { id: p(8), name: 'Lena Nguyen', email: 'lena.n@test.com', phone: '(503) 555-0108', trade: 'Plumbing', secondaryTrades: [], rating: 4.4, reviewCount: 27, hourlyRateMinCents: 7000, hourlyRateMaxCents: 10500, city: 'Portland', state: 'OR', yearsExperience: 7, tier: 'bronze', available: false, bio: 'Eco-conscious plumber focused on water-saving fixtures and greywater systems.', specialties: ['water filtration', 'fixture install', 'leak detection'], licenseVerified: true, insuranceVerified: true },
  { id: p(9), name: 'Frank Kowalski', email: 'frank.k@test.com', phone: '(312) 555-0109', trade: 'Plumbing', secondaryTrades: ['HVAC'], rating: 4.7, reviewCount: 63, hourlyRateMinCents: 8000, hourlyRateMaxCents: 12000, city: 'Chicago', state: 'IL', yearsExperience: 16, tier: 'silver', available: true, bio: 'Chicago-area plumbing and HVAC crossover specialist. Commercial and residential.', specialties: ['water heater', 'sump pump', 'drain cleaning'], licenseVerified: true, insuranceVerified: true },
  { id: p(10), name: 'Aisha Jackson', email: 'aisha.j@test.com', phone: '(615) 555-0110', trade: 'Plumbing', secondaryTrades: [], rating: 4.2, reviewCount: 11, hourlyRateMinCents: 6000, hourlyRateMaxCents: 9000, city: 'Nashville', state: 'TN', yearsExperience: 3, tier: 'bronze', available: true, bio: 'Up-and-coming plumber building a reputation on quality work and communication.', specialties: ['pipe repair', 'fixture install', 'drain cleaning'], licenseVerified: true, insuranceVerified: false },

  // ── Painting (10) ─────────────────────────────────────────────────
  { id: p(11), name: 'Diana Brooks', email: 'diana.b@test.com', phone: '(720) 555-0111', trade: 'Painting', secondaryTrades: ['Drywall'], rating: 4.8, reviewCount: 68, hourlyRateMinCents: 5500, hourlyRateMaxCents: 8500, city: 'Denver', state: 'CO', yearsExperience: 14, tier: 'gold', available: true, bio: 'Interior and exterior painting with an eye for detail. Color consultation included.', specialties: ['interior', 'exterior', 'color consultation'], licenseVerified: true, insuranceVerified: true },
  { id: p(12), name: 'Omar Hassan', email: 'omar.h@test.com', phone: '(602) 555-0112', trade: 'Painting', secondaryTrades: [], rating: 4.6, reviewCount: 45, hourlyRateMinCents: 5000, hourlyRateMaxCents: 8000, city: 'Phoenix', state: 'AZ', yearsExperience: 10, tier: 'silver', available: true, bio: 'Residential painting specialist — interiors, cabinets, and deck staining.', specialties: ['cabinet refinishing', 'deck stain', 'interior'], licenseVerified: true, insuranceVerified: true },
  { id: p(13), name: 'Tanya Williams', email: 'tanya.w@test.com', phone: '(704) 555-0113', trade: 'Painting', secondaryTrades: ['Wallpaper'], rating: 4.9, reviewCount: 103, hourlyRateMinCents: 6000, hourlyRateMaxCents: 9500, city: 'Charlotte', state: 'NC', yearsExperience: 19, tier: 'gold', available: true, bio: 'Award-winning painter and wallpaper installer. Residential and boutique commercial.', specialties: ['wallpaper', 'exterior', 'commercial'], licenseVerified: true, insuranceVerified: true },
  { id: p(14), name: 'Ben Murphy', email: 'ben.m@test.com', phone: '(617) 555-0114', trade: 'Painting', secondaryTrades: ['Drywall'], rating: 4.4, reviewCount: 28, hourlyRateMinCents: 5500, hourlyRateMaxCents: 8000, city: 'Boston', state: 'MA', yearsExperience: 6, tier: 'bronze', available: false, bio: 'Interior painter focused on drywall repair and texture matching.', specialties: ['drywall repair', 'texture', 'interior'], licenseVerified: true, insuranceVerified: true },
  { id: p(15), name: 'Lucia Fernandez', email: 'lucia.f@test.com', phone: '(210) 555-0115', trade: 'Painting', secondaryTrades: [], rating: 4.5, reviewCount: 36, hourlyRateMinCents: 4500, hourlyRateMaxCents: 7500, city: 'San Antonio', state: 'TX', yearsExperience: 9, tier: 'silver', available: true, bio: 'Full-service painting — from prep to final coat. Pressure wash prep included on exteriors.', specialties: ['exterior', 'pressure wash prep', 'deck stain'], licenseVerified: true, insuranceVerified: true },
  { id: p(16), name: 'Chris Tanaka', email: 'chris.t@test.com', phone: '(415) 555-0116', trade: 'Painting', secondaryTrades: [], rating: 4.7, reviewCount: 52, hourlyRateMinCents: 6500, hourlyRateMaxCents: 10000, city: 'San Francisco', state: 'CA', yearsExperience: 12, tier: 'silver', available: true, bio: 'Bay Area painting pro. Victorian homes, modern condos, and commercial spaces.', specialties: ['commercial', 'interior', 'cabinet refinishing'], licenseVerified: true, insuranceVerified: true },
  { id: p(17), name: 'Derek Washington', email: 'derek.w@test.com', phone: '(313) 555-0117', trade: 'Painting', secondaryTrades: ['Pressure Washing'], rating: 4.3, reviewCount: 15, hourlyRateMinCents: 4500, hourlyRateMaxCents: 7000, city: 'Detroit', state: 'MI', yearsExperience: 4, tier: 'bronze', available: true, bio: 'Growing my painting business one happy customer at a time. Interior and exterior.', specialties: ['interior', 'exterior', 'pressure wash prep'], licenseVerified: false, insuranceVerified: true },
  { id: p(18), name: 'Natasha Petrov', email: 'natasha.p@test.com', phone: '(952) 555-0118', trade: 'Painting', secondaryTrades: [], rating: 4.6, reviewCount: 40, hourlyRateMinCents: 5000, hourlyRateMaxCents: 8000, city: 'Minneapolis', state: 'MN', yearsExperience: 11, tier: 'silver', available: true, bio: 'Detail-oriented painter. Neat lines, no mess. Interior and cabinet specialist.', specialties: ['interior', 'cabinet refinishing', 'color consultation'], licenseVerified: true, insuranceVerified: true },
  { id: p(19), name: 'Ryan Gallagher', email: 'ryan.g@test.com', phone: '(503) 555-0119', trade: 'Painting', secondaryTrades: [], rating: 4.8, reviewCount: 71, hourlyRateMinCents: 5500, hourlyRateMaxCents: 9000, city: 'Portland', state: 'OR', yearsExperience: 15, tier: 'gold', available: false, bio: 'Low-VOC and eco-friendly painting for health-conscious homeowners.', specialties: ['interior', 'exterior', 'commercial'], licenseVerified: true, insuranceVerified: true },
  { id: p(20), name: 'Jasmine Lewis', email: 'jasmine.l@test.com', phone: '(919) 555-0120', trade: 'Painting', secondaryTrades: [], rating: 4.5, reviewCount: 33, hourlyRateMinCents: 5000, hourlyRateMaxCents: 7500, city: 'Raleigh', state: 'NC', yearsExperience: 7, tier: 'bronze', available: true, bio: 'Residential painter with a knack for transforming spaces. Free estimates.', specialties: ['interior', 'deck stain', 'drywall repair'], licenseVerified: true, insuranceVerified: true },

  // ── Carpentry (10) ────────────────────────────────────────────────
  { id: p(21), name: 'Kevin O\'Brien', email: 'kevin.ob@test.com', phone: '(206) 555-0121', trade: 'Carpentry', secondaryTrades: ['Decks', 'Fencing'], rating: 4.7, reviewCount: 58, hourlyRateMinCents: 7500, hourlyRateMaxCents: 11000, city: 'Seattle', state: 'WA', yearsExperience: 15, tier: 'silver', available: true, bio: 'Finish carpenter and deck builder. Custom trim, built-ins, and outdoor living.', specialties: ['trim/finish', 'decks', 'shelving'], licenseVerified: true, insuranceVerified: true },
  { id: p(22), name: 'Ray Patterson', email: 'ray.p@test.com', phone: '(603) 555-0122', trade: 'Carpentry', secondaryTrades: [], rating: 4.9, reviewCount: 110, hourlyRateMinCents: 8500, hourlyRateMaxCents: 13000, city: 'Manchester', state: 'NH', yearsExperience: 25, tier: 'gold', available: true, bio: '25 years of structural and finish carpentry. From framing to crown molding.', specialties: ['framing', 'stairs', 'structural repair'], licenseVerified: true, insuranceVerified: true },
  { id: p(23), name: 'Sofia Martinez', email: 'sofia.m@test.com', phone: '(214) 555-0123', trade: 'Carpentry', secondaryTrades: ['Furniture Repair'], rating: 4.6, reviewCount: 39, hourlyRateMinCents: 6500, hourlyRateMaxCents: 10000, city: 'Dallas', state: 'TX', yearsExperience: 9, tier: 'silver', available: true, bio: 'Custom cabinetry and furniture repair. Bringing craftsmanship back to Texas homes.', specialties: ['cabinets', 'furniture repair', 'doors'], licenseVerified: true, insuranceVerified: true },
  { id: p(24), name: 'Earl Henderson', email: 'earl.h@test.com', phone: '(901) 555-0124', trade: 'Carpentry', secondaryTrades: [], rating: 4.4, reviewCount: 22, hourlyRateMinCents: 6000, hourlyRateMaxCents: 9000, city: 'Memphis', state: 'TN', yearsExperience: 7, tier: 'bronze', available: true, bio: 'Reliable carpenter for door hanging, window installs, and trim work.', specialties: ['doors', 'windows', 'trim/finish'], licenseVerified: true, insuranceVerified: true },
  { id: p(25), name: 'Hannah Schmidt', email: 'hannah.s@test.com', phone: '(303) 555-0125', trade: 'Carpentry', secondaryTrades: ['Decks'], rating: 4.8, reviewCount: 76, hourlyRateMinCents: 8000, hourlyRateMaxCents: 12000, city: 'Boulder', state: 'CO', yearsExperience: 17, tier: 'gold', available: true, bio: 'Mountain-town carpenter specializing in decks, pergolas, and custom built-ins.', specialties: ['decks', 'shelving', 'trim/finish'], licenseVerified: true, insuranceVerified: true },
  { id: p(26), name: 'Jerome Davis', email: 'jerome.d@test.com', phone: '(504) 555-0126', trade: 'Carpentry', secondaryTrades: [], rating: 4.3, reviewCount: 16, hourlyRateMinCents: 5500, hourlyRateMaxCents: 8500, city: 'New Orleans', state: 'LA', yearsExperience: 4, tier: 'bronze', available: false, bio: 'Specializing in historic home restoration and structural carpentry.', specialties: ['structural repair', 'framing', 'stairs'], licenseVerified: true, insuranceVerified: false },
  { id: p(27), name: 'Megan Cole', email: 'megan.c@test.com', phone: '(480) 555-0127', trade: 'Carpentry', secondaryTrades: ['Fencing'], rating: 4.5, reviewCount: 30, hourlyRateMinCents: 6500, hourlyRateMaxCents: 9500, city: 'Scottsdale', state: 'AZ', yearsExperience: 8, tier: 'silver', available: true, bio: 'Desert-climate carpentry — pergolas, shade structures, fencing, and custom work.', specialties: ['decks', 'doors', 'cabinets'], licenseVerified: true, insuranceVerified: true },
  { id: p(28), name: 'Nate Kim', email: 'nate.k@test.com', phone: '(808) 555-0128', trade: 'Carpentry', secondaryTrades: [], rating: 4.7, reviewCount: 48, hourlyRateMinCents: 8000, hourlyRateMaxCents: 12500, city: 'Honolulu', state: 'HI', yearsExperience: 13, tier: 'silver', available: true, bio: 'Island carpenter — humidity-resistant materials, lanai builds, and tropical custom work.', specialties: ['framing', 'decks', 'windows'], licenseVerified: true, insuranceVerified: true },
  { id: p(29), name: 'Victor Alonso', email: 'victor.a@test.com', phone: '(954) 555-0129', trade: 'Carpentry', secondaryTrades: [], rating: 4.2, reviewCount: 9, hourlyRateMinCents: 5500, hourlyRateMaxCents: 8500, city: 'Fort Lauderdale', state: 'FL', yearsExperience: 3, tier: 'bronze', available: true, bio: 'Young carpenter eager to prove himself. Clean work, on time, every time.', specialties: ['trim/finish', 'shelving', 'doors'], licenseVerified: true, insuranceVerified: true },
  { id: p(30), name: 'Beth Yamamoto', email: 'beth.y@test.com', phone: '(916) 555-0130', trade: 'Carpentry', secondaryTrades: ['Furniture Repair'], rating: 4.6, reviewCount: 44, hourlyRateMinCents: 7000, hourlyRateMaxCents: 10500, city: 'Sacramento', state: 'CA', yearsExperience: 11, tier: 'silver', available: true, bio: 'Cabinet maker and finish carpenter. Custom kitchens and built-in storage.', specialties: ['cabinets', 'furniture repair', 'shelving'], licenseVerified: true, insuranceVerified: true },

  // ── Smart Home / Technology (10) ──────────────────────────────────
  { id: p(31), name: 'Tyler Brennan', email: 'tyler.b@test.com', phone: '(512) 555-0131', trade: 'Smart Home', secondaryTrades: ['Electrical'], rating: 4.8, reviewCount: 65, hourlyRateMinCents: 9000, hourlyRateMaxCents: 15000, city: 'Austin', state: 'TX', yearsExperience: 10, tier: 'gold', available: true, bio: 'Full smart home integration — Lutron, Control4, and Savant certified.', specialties: ['smart lighting', 'home networking', 'whole-home audio'], licenseVerified: true, insuranceVerified: true },
  { id: p(32), name: 'Andrea Kim', email: 'andrea.k@test.com', phone: '(425) 555-0132', trade: 'Smart Home', secondaryTrades: [], rating: 4.6, reviewCount: 38, hourlyRateMinCents: 8000, hourlyRateMaxCents: 13000, city: 'Bellevue', state: 'WA', yearsExperience: 7, tier: 'silver', available: true, bio: 'Smart home specialist with a focus on networking, WiFi mesh, and security cameras.', specialties: ['home networking', 'security cameras', 'smart thermostats'], licenseVerified: true, insuranceVerified: true },
  { id: p(33), name: 'Dwayne Mitchell', email: 'dwayne.m@test.com', phone: '(470) 555-0133', trade: 'Smart Home', secondaryTrades: ['Security'], rating: 4.5, reviewCount: 29, hourlyRateMinCents: 7500, hourlyRateMaxCents: 12000, city: 'Atlanta', state: 'GA', yearsExperience: 6, tier: 'silver', available: true, bio: 'Access control and security camera installs for homes and small businesses.', specialties: ['security cameras', 'access control', 'structured wiring'], licenseVerified: true, insuranceVerified: true },
  { id: p(34), name: 'Rachel Stein', email: 'rachel.s@test.com', phone: '(858) 555-0134', trade: 'Smart Home', secondaryTrades: [], rating: 4.9, reviewCount: 82, hourlyRateMinCents: 10000, hourlyRateMaxCents: 16000, city: 'San Diego', state: 'CA', yearsExperience: 14, tier: 'gold', available: false, bio: 'Premium smart home design and install. Automated blinds, lighting scenes, whole-home audio.', specialties: ['automated blinds', 'smart lighting', 'whole-home audio'], licenseVerified: true, insuranceVerified: true },
  { id: p(35), name: 'Matt Harper', email: 'matt.h@test.com', phone: '(303) 555-0135', trade: 'Smart Home', secondaryTrades: ['Electrical'], rating: 4.4, reviewCount: 20, hourlyRateMinCents: 7000, hourlyRateMaxCents: 11000, city: 'Denver', state: 'CO', yearsExperience: 4, tier: 'bronze', available: true, bio: 'EV charger installs and smart home basics — thermostats, doorbells, cameras.', specialties: ['EV charger install', 'smart thermostats', 'TV mounting'], licenseVerified: true, insuranceVerified: true },
  { id: p(36), name: 'Zara Okafor', email: 'zara.o@test.com', phone: '(240) 555-0136', trade: 'Smart Home', secondaryTrades: [], rating: 4.7, reviewCount: 51, hourlyRateMinCents: 8500, hourlyRateMaxCents: 14000, city: 'Bethesda', state: 'MD', yearsExperience: 9, tier: 'silver', available: true, bio: 'D.C. area smart home pro — structured wiring, home theater, and automation.', specialties: ['structured wiring', 'whole-home audio', 'home networking'], licenseVerified: true, insuranceVerified: true },
  { id: p(37), name: 'Logan Pierce', email: 'logan.p@test.com', phone: '(615) 555-0137', trade: 'Smart Home', secondaryTrades: [], rating: 4.3, reviewCount: 14, hourlyRateMinCents: 6500, hourlyRateMaxCents: 10000, city: 'Nashville', state: 'TN', yearsExperience: 3, tier: 'bronze', available: true, bio: 'TV mounting, soundbar installs, and basic smart home setup. Fast and tidy.', specialties: ['TV mounting', 'smart lighting', 'smart thermostats'], licenseVerified: false, insuranceVerified: true },
  { id: p(38), name: 'Irene Cho', email: 'irene.c@test.com', phone: '(650) 555-0138', trade: 'Smart Home', secondaryTrades: ['Electrical'], rating: 4.6, reviewCount: 42, hourlyRateMinCents: 9000, hourlyRateMaxCents: 14500, city: 'Palo Alto', state: 'CA', yearsExperience: 8, tier: 'silver', available: true, bio: 'Silicon Valley smart home integrator. Enterprise-grade WiFi and automation.', specialties: ['home networking', 'automated blinds', 'security cameras'], licenseVerified: true, insuranceVerified: true },
  { id: p(39), name: 'Craig Foster', email: 'craig.f@test.com', phone: '(813) 555-0139', trade: 'Smart Home', secondaryTrades: [], rating: 4.5, reviewCount: 25, hourlyRateMinCents: 7000, hourlyRateMaxCents: 11500, city: 'Tampa', state: 'FL', yearsExperience: 5, tier: 'bronze', available: true, bio: 'Smart home installs for new construction and retrofits. Clean cable runs guaranteed.', specialties: ['structured wiring', 'EV charger install', 'access control'], licenseVerified: true, insuranceVerified: true },
  { id: p(40), name: 'Simone Baptiste', email: 'simone.b@test.com', phone: '(504) 555-0140', trade: 'Smart Home', secondaryTrades: ['Security'], rating: 4.8, reviewCount: 60, hourlyRateMinCents: 8500, hourlyRateMaxCents: 13500, city: 'New Orleans', state: 'LA', yearsExperience: 11, tier: 'gold', available: true, bio: 'Security and smart home specialist. Ring, Nest, and custom solutions.', specialties: ['security cameras', 'access control', 'smart lighting'], licenseVerified: true, insuranceVerified: true },

  // ── Electrical (10) ───────────────────────────────────────────────
  { id: p(41), name: 'Sarah Chen', email: 'sarah.c@test.com', phone: '(512) 555-0141', trade: 'Electrical', secondaryTrades: ['Smart Home'], rating: 4.9, reviewCount: 95, hourlyRateMinCents: 9000, hourlyRateMaxCents: 14000, city: 'Austin', state: 'TX', yearsExperience: 16, tier: 'gold', available: true, bio: 'Master electrician — panel upgrades, rewiring, and EV charger installs.', specialties: ['panel upgrade', 'EV charger', 'rewiring'], licenseVerified: true, insuranceVerified: true },
  { id: p(42), name: 'William Grant', email: 'william.g@test.com', phone: '(603) 555-0142', trade: 'Electrical', secondaryTrades: [], rating: 4.7, reviewCount: 67, hourlyRateMinCents: 8500, hourlyRateMaxCents: 12500, city: 'Nashua', state: 'NH', yearsExperience: 20, tier: 'gold', available: true, bio: 'Licensed NH electrician. Code compliance, generator installs, and commercial work.', specialties: ['code compliance', 'generator', 'lighting install'], licenseVerified: true, insuranceVerified: true },
  { id: p(43), name: 'Michelle Park', email: 'michelle.p@test.com', phone: '(469) 555-0143', trade: 'Electrical', secondaryTrades: [], rating: 4.5, reviewCount: 34, hourlyRateMinCents: 7500, hourlyRateMaxCents: 11000, city: 'Plano', state: 'TX', yearsExperience: 8, tier: 'silver', available: true, bio: 'Residential electrical specialist — outlets, switches, ceiling fans, lighting.', specialties: ['outlet/switch', 'ceiling fan', 'lighting install'], licenseVerified: true, insuranceVerified: true },
  { id: p(44), name: 'Andre Mitchell', email: 'andre.m@test.com', phone: '(718) 555-0144', trade: 'Electrical', secondaryTrades: [], rating: 4.6, reviewCount: 48, hourlyRateMinCents: 9500, hourlyRateMaxCents: 14500, city: 'Queens', state: 'NY', yearsExperience: 13, tier: 'silver', available: true, bio: 'NYC-licensed electrician. Panel upgrades, code corrections, and surge protection.', specialties: ['panel upgrade', 'surge protection', 'code compliance'], licenseVerified: true, insuranceVerified: true },
  { id: p(45), name: 'Rosa Gutierrez', email: 'rosa.g@test.com', phone: '(602) 555-0145', trade: 'Electrical', secondaryTrades: ['Solar'], rating: 4.8, reviewCount: 72, hourlyRateMinCents: 8500, hourlyRateMaxCents: 13000, city: 'Phoenix', state: 'AZ', yearsExperience: 15, tier: 'gold', available: false, bio: 'Arizona electrician and solar installer. Keeping homes cool and powered.', specialties: ['EV charger', 'lighting install', 'landscape lighting'], licenseVerified: true, insuranceVerified: true },
  { id: p(46), name: 'Brian Kelly', email: 'brian.k@test.com', phone: '(847) 555-0146', trade: 'Electrical', secondaryTrades: [], rating: 4.3, reviewCount: 18, hourlyRateMinCents: 7000, hourlyRateMaxCents: 10000, city: 'Evanston', state: 'IL', yearsExperience: 5, tier: 'bronze', available: true, bio: 'Journeyman electrician tackling residential outlets, fans, and fixture swaps.', specialties: ['outlet/switch', 'ceiling fan', 'surge protection'], licenseVerified: true, insuranceVerified: true },
  { id: p(47), name: 'Tamara Webb', email: 'tamara.w@test.com', phone: '(404) 555-0147', trade: 'Electrical', secondaryTrades: [], rating: 4.4, reviewCount: 25, hourlyRateMinCents: 7500, hourlyRateMaxCents: 11500, city: 'Decatur', state: 'GA', yearsExperience: 6, tier: 'bronze', available: true, bio: 'Reliable electrical work for metro Atlanta homes. No job too small.', specialties: ['lighting install', 'outlet/switch', 'ceiling fan'], licenseVerified: true, insuranceVerified: true },
  { id: p(48), name: 'Dan Sorensen', email: 'dan.s@test.com', phone: '(612) 555-0148', trade: 'Electrical', secondaryTrades: ['Generator'], rating: 4.7, reviewCount: 55, hourlyRateMinCents: 8000, hourlyRateMaxCents: 12000, city: 'Minneapolis', state: 'MN', yearsExperience: 18, tier: 'silver', available: true, bio: 'Generator specialist and general electrician. Minnesota winters demand reliable power.', specialties: ['generator', 'panel upgrade', 'rewiring'], licenseVerified: true, insuranceVerified: true },
  { id: p(49), name: 'Yuki Tanaka', email: 'yuki.t@test.com', phone: '(408) 555-0149', trade: 'Electrical', secondaryTrades: [], rating: 4.5, reviewCount: 31, hourlyRateMinCents: 9000, hourlyRateMaxCents: 14000, city: 'San Jose', state: 'CA', yearsExperience: 10, tier: 'silver', available: true, bio: 'Bay Area electrician — landscape lighting, EV chargers, and whole-house rewires.', specialties: ['landscape lighting', 'EV charger', 'rewiring'], licenseVerified: true, insuranceVerified: true },
  { id: p(50), name: 'Patrick O\'Neal', email: 'patrick.on@test.com', phone: '(617) 555-0150', trade: 'Electrical', secondaryTrades: [], rating: 4.2, reviewCount: 8, hourlyRateMinCents: 6500, hourlyRateMaxCents: 9500, city: 'Cambridge', state: 'MA', yearsExperience: 2, tier: 'bronze', available: true, bio: 'Recently licensed electrician building my client base. Quality work, fair rates.', specialties: ['outlet/switch', 'lighting install', 'ceiling fan'], licenseVerified: true, insuranceVerified: false },

  // ── Landscaping (10) ──────────────────────────────────────────────
  { id: p(51), name: 'Maria Santos', email: 'maria.s@test.com', phone: '(404) 555-0151', trade: 'Landscaping', secondaryTrades: ['Tree Service'], rating: 4.9, reviewCount: 120, hourlyRateMinCents: 5500, hourlyRateMaxCents: 9000, city: 'Atlanta', state: 'GA', yearsExperience: 20, tier: 'gold', available: true, bio: 'Full-service landscaping company. Design, install, and seasonal maintenance.', specialties: ['garden design', 'hardscape/patio', 'seasonal cleanup'], licenseVerified: true, insuranceVerified: true },
  { id: p(52), name: 'Greg Thornton', email: 'greg.t@test.com', phone: '(603) 555-0152', trade: 'Landscaping', secondaryTrades: ['Snow Removal'], rating: 4.6, reviewCount: 43, hourlyRateMinCents: 4500, hourlyRateMaxCents: 7500, city: 'Exeter', state: 'NH', yearsExperience: 12, tier: 'silver', available: true, bio: 'New England landscaper — mowing, plowing, hardscaping, and everything in between.', specialties: ['lawn maintenance', 'snow removal', 'retaining walls'], licenseVerified: true, insuranceVerified: true },
  { id: p(53), name: 'Janet Liu', email: 'janet.l@test.com', phone: '(503) 555-0153', trade: 'Landscaping', secondaryTrades: [], rating: 4.7, reviewCount: 57, hourlyRateMinCents: 5000, hourlyRateMaxCents: 8500, city: 'Portland', state: 'OR', yearsExperience: 14, tier: 'gold', available: true, bio: 'Pacific NW native plant specialist. Sustainable garden design and rain gardens.', specialties: ['garden design', 'irrigation', 'drainage'], licenseVerified: true, insuranceVerified: true },
  { id: p(54), name: 'Carlos Moreno', email: 'carlos.mo@test.com', phone: '(210) 555-0154', trade: 'Landscaping', secondaryTrades: ['Irrigation'], rating: 4.5, reviewCount: 35, hourlyRateMinCents: 4000, hourlyRateMaxCents: 7000, city: 'San Antonio', state: 'TX', yearsExperience: 10, tier: 'silver', available: true, bio: 'Texas heat requires smart irrigation. Drip systems, sprinkler repair, and xeriscape.', specialties: ['irrigation', 'lawn maintenance', 'outdoor lighting'], licenseVerified: true, insuranceVerified: true },
  { id: p(55), name: 'Kim Pham', email: 'kim.p@test.com', phone: '(714) 555-0155', trade: 'Landscaping', secondaryTrades: [], rating: 4.4, reviewCount: 26, hourlyRateMinCents: 5000, hourlyRateMaxCents: 8000, city: 'Irvine', state: 'CA', yearsExperience: 7, tier: 'bronze', available: false, bio: 'SoCal landscaper focused on drought-tolerant designs and hardscaping.', specialties: ['hardscape/patio', 'garden design', 'outdoor lighting'], licenseVerified: true, insuranceVerified: true },
  { id: p(56), name: 'Travis Morrison', email: 'travis.m@test.com', phone: '(816) 555-0156', trade: 'Landscaping', secondaryTrades: ['Fencing'], rating: 4.3, reviewCount: 17, hourlyRateMinCents: 4000, hourlyRateMaxCents: 6500, city: 'Kansas City', state: 'MO', yearsExperience: 5, tier: 'bronze', available: true, bio: 'Lawn care and basic landscaping for residential properties. Weekly plans available.', specialties: ['lawn maintenance', 'seasonal cleanup', 'tree service'], licenseVerified: true, insuranceVerified: true },
  { id: p(57), name: 'Destiny Harris', email: 'destiny.h@test.com', phone: '(901) 555-0157', trade: 'Landscaping', secondaryTrades: [], rating: 4.6, reviewCount: 40, hourlyRateMinCents: 4500, hourlyRateMaxCents: 7500, city: 'Memphis', state: 'TN', yearsExperience: 9, tier: 'silver', available: true, bio: 'Creating beautiful outdoor spaces in the Mid-South. Patios, lighting, and gardens.', specialties: ['hardscape/patio', 'outdoor lighting', 'garden design'], licenseVerified: true, insuranceVerified: true },
  { id: p(58), name: 'Pete Andersen', email: 'pete.a@test.com', phone: '(303) 555-0158', trade: 'Landscaping', secondaryTrades: ['Snow Removal'], rating: 4.8, reviewCount: 78, hourlyRateMinCents: 5500, hourlyRateMaxCents: 9500, city: 'Denver', state: 'CO', yearsExperience: 16, tier: 'gold', available: true, bio: 'Year-round landscape and snow removal. Retaining walls, drainage, and seasonal contracts.', specialties: ['retaining walls', 'drainage', 'snow removal'], licenseVerified: true, insuranceVerified: true },
  { id: p(59), name: 'Nina Rossi', email: 'nina.r@test.com', phone: '(857) 555-0159', trade: 'Landscaping', secondaryTrades: [], rating: 4.5, reviewCount: 33, hourlyRateMinCents: 5000, hourlyRateMaxCents: 8000, city: 'Boston', state: 'MA', yearsExperience: 8, tier: 'silver', available: true, bio: 'New England landscape designer. From spring plantings to fall cleanups.', specialties: ['garden design', 'seasonal cleanup', 'lawn maintenance'], licenseVerified: true, insuranceVerified: true },
  { id: p(60), name: 'Roberto Campos', email: 'roberto.c@test.com', phone: '(305) 555-0160', trade: 'Landscaping', secondaryTrades: ['Tree Service'], rating: 4.7, reviewCount: 52, hourlyRateMinCents: 5000, hourlyRateMaxCents: 8500, city: 'Miami', state: 'FL', yearsExperience: 13, tier: 'silver', available: true, bio: 'Tropical landscaping expert. Palm trimming, sod installs, and hurricane cleanup.', specialties: ['tree service', 'lawn maintenance', 'irrigation'], licenseVerified: true, insuranceVerified: true },

  // ── Installation / General (10) ───────────────────────────────────
  { id: p(61), name: 'James Wilson', email: 'james.w@test.com', phone: '(813) 555-0161', trade: 'Installation', secondaryTrades: ['HVAC'], rating: 4.8, reviewCount: 84, hourlyRateMinCents: 7500, hourlyRateMaxCents: 12000, city: 'Tampa', state: 'FL', yearsExperience: 15, tier: 'gold', available: true, bio: 'HVAC and appliance installation specialist. Certified on all major brands.', specialties: ['HVAC install', 'appliance install', 'water heater'], licenseVerified: true, insuranceVerified: true },
  { id: p(62), name: 'Angela Pope', email: 'angela.p@test.com', phone: '(614) 555-0162', trade: 'Installation', secondaryTrades: ['Flooring'], rating: 4.6, reviewCount: 47, hourlyRateMinCents: 6500, hourlyRateMaxCents: 10500, city: 'Columbus', state: 'OH', yearsExperience: 11, tier: 'silver', available: true, bio: 'Flooring and tile installation. Hardwood, LVP, ceramic, and natural stone.', specialties: ['flooring', 'tile', 'fixture install'], licenseVerified: true, insuranceVerified: true },
  { id: p(63), name: 'Tommy Tran', email: 'tommy.t@test.com', phone: '(703) 555-0163', trade: 'Installation', secondaryTrades: [], rating: 4.5, reviewCount: 31, hourlyRateMinCents: 6000, hourlyRateMaxCents: 9500, city: 'Arlington', state: 'VA', yearsExperience: 8, tier: 'silver', available: true, bio: 'General installer — fencing, gutters, garage doors, and fixture swaps.', specialties: ['fencing', 'gutter install', 'garage door'], licenseVerified: true, insuranceVerified: true },
  { id: p(64), name: 'Heather Blake', email: 'heather.b@test.com', phone: '(919) 555-0164', trade: 'Installation', secondaryTrades: ['Insulation'], rating: 4.4, reviewCount: 22, hourlyRateMinCents: 5500, hourlyRateMaxCents: 8500, city: 'Raleigh', state: 'NC', yearsExperience: 6, tier: 'bronze', available: true, bio: 'Insulation and general installs. Attic, crawlspace, and weatherization.', specialties: ['insulation', 'fixture install', 'water heater'], licenseVerified: true, insuranceVerified: true },
  { id: p(65), name: 'Marcus Bell', email: 'marcus.b@test.com', phone: '(317) 555-0165', trade: 'Installation', secondaryTrades: [], rating: 4.7, reviewCount: 56, hourlyRateMinCents: 7000, hourlyRateMaxCents: 11000, city: 'Indianapolis', state: 'IN', yearsExperience: 14, tier: 'gold', available: true, bio: 'Appliance and fixture installation pro. Same-day service for most installs.', specialties: ['appliance install', 'fixture install', 'water heater'], licenseVerified: true, insuranceVerified: true },
  { id: p(66), name: 'Samantha Reed', email: 'samantha.r@test.com', phone: '(801) 555-0166', trade: 'Installation', secondaryTrades: ['Tile'], rating: 4.3, reviewCount: 15, hourlyRateMinCents: 5500, hourlyRateMaxCents: 8500, city: 'Salt Lake City', state: 'UT', yearsExperience: 4, tier: 'bronze', available: true, bio: 'Tile and flooring installs. Bathrooms, kitchens, and backsplashes.', specialties: ['tile', 'flooring', 'fixture install'], licenseVerified: true, insuranceVerified: false },
  { id: p(67), name: 'Devon Clarke', email: 'devon.c@test.com', phone: '(410) 555-0167', trade: 'Installation', secondaryTrades: [], rating: 4.6, reviewCount: 39, hourlyRateMinCents: 6500, hourlyRateMaxCents: 10000, city: 'Baltimore', state: 'MD', yearsExperience: 9, tier: 'silver', available: false, bio: 'Garage door and fencing specialist. Quality hardware, clean installs.', specialties: ['garage door', 'fencing', 'gutter install'], licenseVerified: true, insuranceVerified: true },
  { id: p(68), name: 'Lisa Chang', email: 'lisa.ch@test.com', phone: '(206) 555-0168', trade: 'Installation', secondaryTrades: ['HVAC'], rating: 4.8, reviewCount: 70, hourlyRateMinCents: 7500, hourlyRateMaxCents: 12000, city: 'Seattle', state: 'WA', yearsExperience: 13, tier: 'gold', available: true, bio: 'HVAC and water heater installation with a focus on energy efficiency.', specialties: ['HVAC install', 'water heater', 'insulation'], licenseVerified: true, insuranceVerified: true },
  { id: p(69), name: 'Oscar Ruiz', email: 'oscar.r@test.com', phone: '(623) 555-0169', trade: 'Installation', secondaryTrades: [], rating: 4.4, reviewCount: 24, hourlyRateMinCents: 5500, hourlyRateMaxCents: 8500, city: 'Glendale', state: 'AZ', yearsExperience: 5, tier: 'bronze', available: true, bio: 'Flooring and general installation. LVP, laminate, and tile. Free estimates.', specialties: ['flooring', 'tile', 'appliance install'], licenseVerified: true, insuranceVerified: true },
  { id: p(70), name: 'Jenny Kim', email: 'jenny.k@test.com', phone: '(602) 555-0170', trade: 'Installation', secondaryTrades: ['Handyman'], rating: 4.7, reviewCount: 61, hourlyRateMinCents: 6000, hourlyRateMaxCents: 9500, city: 'Phoenix', state: 'AZ', yearsExperience: 10, tier: 'silver', available: true, bio: 'General handyman and installer. If it needs putting together or fixing, I am your person.', specialties: ['fixture install', 'appliance install', 'garage door'], licenseVerified: true, insuranceVerified: true },
];

/** Get all unique trade categories from the seeded pros */
export function getTradeCategories(): string[] {
  const trades = new Set<string>();
  SEEDED_PROS.forEach((p) => {
    trades.add(p.trade);
    p.secondaryTrades.forEach((t) => trades.add(t));
  });
  return Array.from(trades).sort();
}

/** Filter pros by trade (checks primary and secondary) */
export function filterProsByTrade(trade: string): SeededPro[] {
  const q = trade.toLowerCase();
  return SEEDED_PROS.filter(
    (p) =>
      p.trade.toLowerCase().includes(q) ||
      p.secondaryTrades.some((t) => t.toLowerCase().includes(q)) ||
      p.specialties.some((s) => s.toLowerCase().includes(q))
  );
}

/** Convert a SeededPro to the client-data Pro interface shape */
export function toClientPro(sp: SeededPro): {
  id: string;
  name: string;
  avatar: string;
  badge: 'gold' | 'silver' | 'bronze' | 'new';
  rating: number;
  reviewCount: number;
  trades: string[];
  distance: string;
  completedJobs: number;
  responseTime: string;
  backgroundChecked: boolean;
  available: boolean;
} {
  const distances = ['0.5 mi', '1.2 mi', '2.3 mi', '3.1 mi', '4.5 mi', '5.8 mi', '6.2 mi', '7.4 mi'];
  const responseTimes = ['< 30 min', '< 1 hour', '< 2 hours', '< 3 hours', '< 4 hours'];

  // Deterministic pseudo-random from id
  const seed = parseInt(sp.id.replace(/\D/g, ''), 10) || 0;

  return {
    id: sp.id,
    name: sp.name,
    avatar: '/icons/avatar-placeholder.svg',
    badge: sp.tier,
    rating: sp.rating,
    reviewCount: sp.reviewCount,
    trades: [sp.trade, ...sp.secondaryTrades],
    distance: distances[seed % distances.length],
    completedJobs: Math.round(sp.reviewCount * 1.8),
    responseTime: responseTimes[seed % responseTimes.length],
    backgroundChecked: sp.licenseVerified && sp.insuranceVerified,
    available: sp.available,
  };
}
